services:
  - type: web
    name: guelmaguide-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_V1_PREFIX
        value: /api/v1
      - key: PROJECT_NAME
        value: Guelma Guide API
      - key: PROJECT_VERSION
        value: 0.1.0
